### ISSUE TITLE
poll function

### ISSUE THREAD

**Issue by iddq** [konkers/sconsole#7]
Hello,

What is the reason for using that poll function instead of simple select()?

Thanks

**Comment by konkers** [comment]
I find the poll() interface nicer to use.  It does not require you to recreate/copy fd_sets each call.

Additionally, under the hood, linux is structured around poll().  In fact you can see that select is implemented in terms of poll() https://github.com/torvalds/linux/blob/v4.10/fs/select.c#L404-L542

**Comment by iddq** [comment]
thanks! is it possible to specify the speed in c_flag or is it an error?
`
        tio.c_cflag = B57600 | CS8 | CLOCAL | CREAD;
        tio.c_ispeed = B57600;
        tio.c_ospeed = B57600;
`

**Comment by konkers** [comment]
My recollection is a bit foggy here but from what I remember: termios has a lot of variation from system to system. You can see that, at the time, I had to not specify it on OSX:

```c
#ifdef __APPLE__
	tio->c_cflag =  CS8 | CLOCAL | CREAD;
#else
	tio->c_cflag =  speed | CS8 | CLOCAL | CREAD;
#endif
```

**Comment by iddq** [comment]
Thanks
